name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install ARM GCC
        run: |
          wget -nv https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
          sudo tar -C /bin/ -xjf gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
          echo "MBED_GCC_ARM_PATH=/bin/gcc-arm-none-eabi-9-2019-q4-major/bin/" >> $GITHUB_ENV

      - name: Install mbed
        run: |
          pip install wheel exdown
          pip install mbed-cli

      - name: Create mbed project
        run: |
          mbed new .
          echo '{"target_overrides":{"*":{"platform.callback-nontrivial":true}}}' > mbed_app.json

      - name: Extract code from README
        run: |
          echo 'import exdown' > extract.py
          echo 'code = exdown.extract("README.md", syntax_filter="cpp")' >> extract.py
          echo 'print(code[0][0])' >> extract.py
          python extract.py > main.cpp

      - name: Compile
        run: |
          mbed compile -t GCC_ARM -m NUCLEO_F103RB
